### ISSUE TITLE
feat-request: allow string to be passed as component

### ISSUE THREAD

**Issue by atchim** [rebelot/heirline.nvim#10]
In the config file for `heirline`, it's very common to have components containing only the `provider` field set to a string, as the following code shows:

```lua
local space =  {provider = ' '}
local align = {provider = '%='}

local statusline = {
  vimode, space, buf, align, file,
}
```

I think would be handy if the plugin allowed a string to be passed as component, as the following code exemplifies:

```lua
local statusline = {
  -- `' '` would be equivalent to `{provider = ' '}`.
  -- The same would apply to `'%='` as well...
  vimode, ' ', buf, '%=', file,
}
```

**Comment by rebelot** [comment]
I agree, it would be handy, but heavily inconsistent. That would require checks almost everywhere. I'd prefer not, but I will consider it anyway. Same goes for numbers and functions defaulting to a provider

**Comment by atchim** [comment]
If this would increase considerably the code complexity, so might be better to leave it as already is...
