### ISSUE TITLE
Percentage provider doesn't update

### ISSUE THREAD

**Issue by fedepujol** [rebelot/heirline.nvim#11]
Hi, Im migrating from feline to heirline and the percentage provider doesn't update when you move the cursor in a file.

It's displaying "Top" in the first 48 lines of a 233 line file. When I reach the bottom it displays "Bottom" but going up It displays "Bottom" for 48 lines up too.

**Comment by rebelot** [comment]
That is exactly what `%P` does.
from `:h statusline`
```
	p N   Percentage through file in lines as in |CTRL-G|.
	P S   Percentage through file of displayed window.  This is like the
	      percentage described for 'ruler'.  Always 3 in length, unless
	      translated.
```
You can rebuild your own using `vim.api.nvim_buf_line_count(0)` & `vim.api.nvim_win_get_cursor(0)` OR you could evaluate `%p` using `vim.api.nvim_eval_statusline()` and then output "top" or "bottom" when the result is 0 or 100

**Comment by fedepujol** [comment]
Oh my bad, didn't know that was the functionality.

Thanks for the help and this is an amazing plugin!
