### ISSUE TITLE
Navic doesn't update in tabline

### ISSUE THREAD

**Issue by boltlessengineer** [rebelot/heirline.nvim#112]
I copied navic section of cookbook, but navic component doesn't work in tabline (tatusline & winbar is fine).

Maybe heirline isn't calling `:redrawtabline` in proper update event?

Fixed with following auto-command but leaving issue for someone having same issue.

```lua
vim.api.nvim_create_autocmd("CursorMoved", {
  command = "redrawtabline",
})
```

**Comment by JerryWhoami** [comment]
The autocmd works like a charm. I had the same issue with the cursor position component in tabline.
