### ISSUE TITLE
Statusline flickering when cursor reach the end of a function.

### ISSUE THREAD

**Issue by AllenDang** [rebelot/heirline.nvim#116]
It's a very strange issue, statusline will flickering when cursor reach the end of a function.

![heirline_issue](https://user-images.githubusercontent.com/18550/220294194-2b630825-cce0-4616-af1e-a2dc700ae841.gif)

I've tested all the component one by one, seems non of them causes the issue.

Any clue why this is happening?

**Comment by rebelot** [comment]
that is `matchup` plugin. check value of `g:matchup_matchparen_offscreen` you can set it to `{ method = 'popup' }` to behave similarly to `treesitter-context`
