### ISSUE TITLE
Issue with Navic

### ISSUE THREAD

**Issue by unphased** [rebelot/heirline.nvim#118]
I used most of the snippets from the cookbook, in the order they were presented, and I probably have a too new version of navic I'm guessing? Need help debugging: 

```
E5108: Error executing lua ...local/share/nvim/lazy/nvim-navic/lua/nvim-navic/init.lua:439: bad argument #3 to '__index' (string expected, got table)
stack traceback:
        [C]: in function '__index'
        ...local/share/nvim/lazy/nvim-navic/lua/nvim-navic/init.lua:439: in function 'condition'
        ...hare/nvim/lazy/heirline.nvim/lua/heirline/statusline.lua:284: in function '_eval'
        ...hare/nvim/lazy/heirline.nvim/lua/heirline/statusline.lua:365: in function '_eval'
        ...hare/nvim/lazy/heirline.nvim/lua/heirline/statusline.lua:365: in function '_eval'
        ...hare/nvim/lazy/heirline.nvim/lua/heirline/statusline.lua:365: in function '_eval'
        ...hare/nvim/lazy/heirline.nvim/lua/heirline/statusline.lua:440: in function 'eval'
        ...ocal/share/nvim/lazy/heirline.nvim/lua/heirline/init.lua:89: in function <...ocal/share/nvim/lazy/heirline.nvim/lua/heirline/init.lua:84>

```
Let me know if details are needed. 

The other bit of info I have now is that simply not including the Navic bar component resolves the error so it's not caused by the navic code. I slightly suspect simply calling setup on navic before running heirline config might do the trick. Will test that now.

**Comment by unphased** [comment]
Is there a _full nerd_ cookbook somewhere? haha. The cookbook is already mighty impressive but definitely getting the hang of how to customize this thing now!

I'll try that out and report back.

**Comment by sidzwans** [comment]
The Heirline's cookbook is good enough. Follow one at a time and try to make sense of the codes.
