### ISSUE TITLE
![ and ] show up inside statusline

### ISSUE THREAD

**Issue by unphased** [rebelot/heirline.nvim#120]
I had to comment these sections from Diagnostic,

```
    -- {
    --     provider = "![",
    -- },
```
to make these chars not appear in the statusline. I'm very curious, what is the `![]` syntax? What interprets it and what does it mean semantically? Hard to search. It's at least apparently not involved in statusline parsing on the nvim side.

**Comment by ghifarit53** [comment]
It's not any special characters I believe, just some kind of separator for the diagnostics section. And you are correct, commenting/removing it to make it disappear from the statusline, will not affect anything
