### ISSUE TITLE
Is there a way to hide tab/bufbar on initial nvim open, when only one buffer and file exists?

### ISSUE THREAD

**Issue by unphased** [rebelot/heirline.nvim#122]
The statusline and winbar both show the filename by default also, further reducing the utility of having it visible in this situation.

**Comment by unphased** [comment]
Sorry for making so many issues. I realize a couple of these could have been better placed in Discussions.

**Comment by ghifarit53** [comment]
There's an option called `showtabline`, and setting it to `1` might fit what you need. You can read more about it in `:h 'showtabline'`

**Comment by rebelot** [comment]
You can do something like this. Will probably add to the cookbook

```lua
-- from the cookbook
local buf_cache = {} -- this
local BufferLine = utils.make_buflist(
    TablineBufferBlock,
    { provider = " ", hl = { fg = "gray" } },
    { provider = " ", hl = { fg = "gray" } }, nil,
    buf_cache -- this
)

vim.api.nvim_create_autocmd({"BufAdd", "BufDelete"}, {
    callback = function()
        if #buf_cache > 1 then
            vim.o.showtabline = 2
        else
            vim.o.showtabline = 1
        end
    end
})
```
