### ISSUE TITLE
Requesting utillity to make spacing better

### ISSUE THREAD

**Issue by unphased** [rebelot/heirline.nvim#123]
In the examples given, there are many `Space` bar items being used. 

The problem with this is that if you have an item in the middle of two Space's that renders empty (e.g. not in a git repo) then two spaces are placed in the bar. 

There should be a way to build a bar that makes adding a space implicit in joining a list, and elides the space that is associated with an empty object.

**Comment by unphased** [comment]
OK perhaps a utility isn't really needed. I am finding that just adhering to the convention of 
- space to the left on all left-aligned components except first
- space tot eh right on all right-aligned components except last

handles the spacing perfectly. 
It is still the case that it would be easier if we didn't have to place the spaces ourselves at all though.

**Comment by gegoune** [comment]
Isn't it what `utils.insert()` is for?

**Comment by unphased** [comment]
I'm not sure. That seems to be inserting stuff to a table. Is there something that joins that uses a delimiter?

**Comment by rebelot** [comment]
You can add the `Space` component _within_ the component itself. A small drawback to this is that you should change the position of the spacers if you shuffle components that are right or left aligned.

```lua
conditional_component = {
  condition = foo(),
  provider = "foo",
  { provider = " "}
}
```

An "automatic" way to concatenate components could be feasible, but probably veery inefficient. I'll think about it
