### ISSUE TITLE
Gruvbox

### ISSUE THREAD

**Issue by saladuit** [rebelot/heirline.nvim#124]
How do I set the correct gruvbox theme?
I chose the dark gruvbox theme but heirline is showing a light version

**Comment by saladuit** [comment]
<img width="1655" alt="Screenshot 2023-03-15 at 16 02 10" src="https://user-images.githubusercontent.com/43225170/225350839-5de1800a-7e79-4150-8192-669ce2c451ef.png">
It looks like this now, and I have to much ocd to live with this

**Comment by rebelot** [comment]
See the color section of the cookbook. You should pick the colors from the highlights you like

**Comment by saladuit** [comment]
@rebelot But why isn't it following the gruvbox dark theme?

**Comment by rebelot** [comment]
How can I help you if I don't know:

1) how you set up your colors
2) what colorscheme you are using (the actual repo implementing gruvbox)

The general rule of thumb is:

1) load your colorscheme `:colo gruvboxwhatever` ___before___ heirline
2) in heirline config, use `utils.get_highlight` to get the colors from highlight groups defined by your colorscheme

**Comment by saladuit** [comment]
I am using astronvim and as far as I know I didn't change any color settings exept:
`  colorscheme = "gruvbox",` the full setting are available on my [dotfiles repo](https://github.com/saladuit/dotfiles/blob/master/astronvim/user/init.lua).
I'm using     ` "ellisonleao/gruvbox.nvim",` as colorscheme.

**Comment by rebelot** [comment]
I am not dissecting your dotfiles man... if you are using default config for astronvim statusline, consider opening an issue there.

**Comment by saladuit** [comment]
I don't expect you to do that.  Is there otherwise a way to force heirline to darkmode? @rebelot I did also open a question on their discord. But didn't get an answer yet

**Comment by saladuit** [comment]
Thank you very much for your extra explanation! I will share your post as well in the Astronvim community! @rebelot

**Comment by bigzhu** [comment]
I have run into the same issue that you described.
@saladuit  Have you found a solution to this issue yet?

**Comment by jamesreprise** [comment]
For anyone running into this, [gruvbox-baby](https://github.com/luisiacc/gruvbox-baby) works well out of the box.
