### ISSUE TITLE
Heirline should refresh winbars on `on_colorscheme` as well

### ISSUE THREAD

**Issue by gegoune** [rebelot/heirline.nvim#127]
Hey, I just noticed that changing colorscheme (or `background`) as described in [cookbook](https://github.com/rebelot/heirline.nvim/blob/master/cookbook.md#theming) nicely reloads them for `statusline` but doesn't for `winbar`s.

It's clear that change gets broadcasted to `statusline` here https://github.com/rebelot/heirline.nvim/blob/9a484130340cd42ff0a12f5a47e31a8c79bfc074/lua/heirline/utils.lua#L399-L401 but the same does not happen for `winbar`s and most likely `tabline` too (but I am barely using colours there to notice) .

Is that something that users could add themselves or would it require change in heirline?

Thanks!

**Comment by rebelot** [comment]
you're right, that needs to be updated. Anyway, I didn't really ever noticed that, and I tested colorscheme changes pretty wildly when developing `kanagawa`.. Resetting the window cache for components is only meaningful for components that get updated on certain autocmd events, which means that, eventually, they'll be refreshed anyway.

**Comment by gegoune** [comment]
Works perfectly, thank you for rapid fix!
