### ISSUE TITLE
Changes after commit 750a112 seem to break `noice.nvim`

### ISSUE THREAD

**Issue by atchim** [rebelot/heirline.nvim#135]
This is my editor in 750a112:

![image](https://user-images.githubusercontent.com/56227607/230750811-6f21d8ca-310b-483d-838e-b5587452d679.png)

This is my editor with changes after 750a112:

![image](https://user-images.githubusercontent.com/56227607/230750837-eec98246-25d2-4f61-ab61-d071c8e165b3.png)

These are the issues I noticed:

- The winbar is shown in the splash screen, which is not desired.
- The floating command window is completely broken. It doesn't display the characters I type.
- Messages aren't shown.

The editor was unusable, so I had to explicitly set the `commit` field with `750a112` in my `lazy.nvim` configuration to be able to use the editor again.

**Comment by rebelot** [comment]
Con you disable the winbar for noice and dashboard file types from the callback option?

**Comment by atchim** [comment]
I was still using the old approach with an autocommand to disable the winbar. Using `disable_winbar_cb` with the proper value fixed this. Thanks for the tip, @rebelot! I wasn't aware of this new functionality.
