### ISSUE TITLE
heirline / wilder woes after 8fb1f07: Receiving error E36 Not enough room

### ISSUE THREAD

**Issue by catgoose** [rebelot/heirline.nvim#136]
nvim -v `NVIM v0.9.0`

![image](https://user-images.githubusercontent.com/21010072/230906952-3ceee781-e11b-46d0-8dbe-8f867519e853.png)

Same issue as #49 

The solution of using
```lua
	require("heirline").setup(StatusLines) --, WinBar)
	require("heirline").winbar = require("heirline.statusline"):new(WinBars)
	vim.opt.winbar = "%{%v:lua.require'heirline'.eval_winbar()%}"
```
does not work as is the fix for issue #49 (https://github.com/rebelot/heirline.nvim/issues/47#issuecomment-1211815471).  Besides I stopped having to use that fix sometime during 0.9 development

Using commit `750a112` does not produce the error.

**Comment by rebelot** [comment]
please see if latest commit fixes the problem
