### ISSUE TITLE
Expandable component types

### ISSUE THREAD

**Issue by arsham** [rebelot/heirline.nvim#14]
The new `experimental` branch which was introduced in #13 is great. However it only accepts a string or a function, which forces the users to change their already made providers.

For example if I want to utilise the `make_elastic_component` function for [this](https://github.com/arsham/arshamiser.nvim/blob/e18411ba7e2dbd2cc96db1a1d986bf6896e2ad48/lua/arshamiser/heirliniser/init.lua#L281..L300) section, I have to change it to this:

```lua
    heirline.make_elastic_component(1, {
      function(self)
        return " " .. (self.icon or "") .. " " .. string.upper(vim.bo.filetype)
      end,
      function(self)
        return " " .. (self.icon or "")
      end,
      "",
    })
```

It would be great if the accepted providers would be tables (`Statusline`?) to make it consistent with the rest of the setup. For example this would be ideal:

```lua
local space = { provider = " " }
{
  hl = function(self)
    return {
      fg = self.icon_color,
      style = "bold",
    }
  end,
  heirline.make_elastic_component(1, {
    {
      space,
      {
        provider = function(self)
          return self.icon or ""
        end,
      },
      space,
      {
        provider = function()
          return string.upper(vim.bo.filetype)
        end,
      },
    },
  },
  {
    space,
    {
      provider = function(self)
        return self.icon or ""
      end,
    },
  },
  "")
}
```

This would be an example or hiding a whole section when there is no space left.

**Comment by rebelot** [comment]
closing this in favor of #13. See updates
