### ISSUE TITLE
invalid highlight color, theming error

### ISSUE THREAD

**Issue by BeeverFeever** [rebelot/heirline.nvim#156]
I have pretty much just copy and pasted from the cookbook, it works except when I open a file in a git repo. I get the error `Invalid highlight color: 'git_add'`. I also get the same error for `git_del` however not `git_change`.

This is my config if it helps: https://pastebin.com/B6H0KrnU

This is the full error in nvim:
```
E5108: Error executing lua ...hare/nvim/lazy/heirline.nvim/lua/heirline/highlights.lua:33: Inval
id highlight color: 'git_add'                                                                   
stack traceback:                                                                                
        [C]: in function 'nvim_set_hl'                                                          
        ...hare/nvim/lazy/heirline.nvim/lua/heirline/highlights.lua:33: in function 'make_hl'   
        ...hare/nvim/lazy/heirline.nvim/lua/heirline/highlights.lua:103: in function 'eval_hl'  
        ...hare/nvim/lazy/heirline.nvim/lua/heirline/statusline.lua:349: in function '_eval'    
        ...hare/nvim/lazy/heirline.nvim/lua/heirline/statusline.lua:365: in function '_eval'    
        ...hare/nvim/lazy/heirline.nvim/lua/heirline/statusline.lua:365: in function '_eval'    
        ...hare/nvim/lazy/heirline.nvim/lua/heirline/statusline.lua:440: in function 'eval'     
        ...ocal/share/nvim/lazy/heirline.nvim/lua/heirline/init.lua:109: in function <...ocal/sh
are/nvim/lazy/heirline.nvim/lua/heirline/init.lua:104>
```

**Comment by pynappo** [comment]
kanagawa likely doesn't define a foreground color for DiffAdded so when `setup_colors()` is run, git_add is set to nil and thus heirline errors when highlighting the git segment. you have multiple options:

- define git_add in `setup_colors()` as some other color (eg. the background of DiffAdded, or the foreground of GitsignsAdd, or some other color from kanagawa's colors)
- don't use git_add at all and just set the highlight of the segment to just be a highlight (ie. `hl = 'DiffAdded'`)

**Comment by BeeverFeever** [comment]
Ahh yeah that makes sense, there probably isn't a forground set for `DiffAdd`. I've just done `hl = 'DiffAdd'` and it works now. Thank you.
