### ISSUE TITLE
Nested flexible component skipped when contrasting

### ISSUE THREAD

**Issue by FelisNivalis** [rebelot/heirline.nvim#161]
A minimal example is as following:
```
statusline = {
  flexible = 1,
  { provider = string.rep("a", 100) },
  {
    { provider = string.rep("d", 10) },
    {
      flexible = true,
      { provider = string.rep("b", 80) },
      { provider = string.rep("c", 10) },
    },
  },
  {} -- empty
}
```
When, for example, the width reduces from 100 to 50, I would expect dc to be shown, but instead nothing is shown.

**Comment by rebelot** [comment]
<img width="1535" alt="Screenshot 2023-08-01 at 15 16 03" src="https://github.com/rebelot/heirline.nvim/assets/36300441/5ef26f94-9510-4160-9456-de6e22d02327">
