### ISSUE TITLE
Example recipe for mode doesn't work with visual block mode

### ISSUE THREAD

**Issue by Azeirah** [rebelot/heirline.nvim#18]
I copied and pasted the recipe to display the current mode, it works well for most modes but it fails for Visual Block.

It gave an error stating that it could not concatenate a null value here

```
    provider = function(self)
        return " %2("..self.mode_names[self.mode].."%)"
    end,
```

**Comment by Azeirah** [comment]
I actually read that and I still didn't do it ;_;

Sorry

**Comment by rebelot** [comment]
Np. I should find a way to replace those characters so that it could be copied as is.
