### ISSUE TITLE
Conditional statusline for `TelescopePrompt`

### ISSUE THREAD

**Issue by pseudoparenchymatous** [rebelot/heirline.nvim#204]
So I want a custom statusline when the telescope window is visible and I tried this:
```lua
condition = function()
  return conditions.buffer_matches({ filetype = { "TelescopePrompt" } })
end
```
but it doesn't work--it used to work on my old config before I rewrote my config.
Now I tried debugging by:
```lua
condition = function()
  vim.print(vim.bo.filetype)
  return false
end
```
but it doesn't even print the filetype "TelescopePrompt"

**Comment by rebelot** [comment]
> it used to work on my old config before I rewrote my config.

this is usually a useful piece of information.

anyway, consider that telescope prompt is a `prompt` buftype, which might be handled differently than the statusline you configured for regular buffers (and this is the case if you followed the cookbook)
