### ISSUE TITLE
Filler character

### ISSUE THREAD

**Issue by simonmandlik** [rebelot/heirline.nvim#215]
Hi, what is the recommended way to fill the rest of statusline with a single character? I know that it is possible to do with spaces, but what if I want to use other character than space?

There are two possible solutions I could think of:

- Using flexible components with a looot of children (providing all possible lengths of the fill), and
- manually computing the length based on other components and window width, which seems that it will be much more efficient.

Thanks!

**Comment by rebelot** [comment]
You are looking for `:h 'fillchars'` `stl` field

**Comment by simonmandlik** [comment]
Thanks for the quick reply :)

I know about `fillchars`, which works fine for "global" fillchars. However, I can't hide statusline e.g. in `NvimTree` buffers

```lua
vim.api.nvim_create_autocmd("FileType", {
    pattern = "NvimTree",
    callback = function()
        local set = vim.opt_local
        set.fillchars = { stl = " ", stlnc = " "  }
    end
})
```

**Comment by simonmandlik** [comment]
It looks like `fillchars` is really a global option, however, I managed to hide the statusline in `NvimTree` like this:

```lua
condition = function()
    return not conditions.buffer_matches {
        filetype = { "NvimTree " },
    }
end,
```

Thanks for the help!
