### ISSUE TITLE
Conflict between abbreviated and extended highlight properties

### ISSUE THREAD

**Issue by atchim** [rebelot/heirline.nvim#26]
I've noticed that setting the foreground color through the `fg` field is ineffective, while setting it through the `foreground` field is the effective way to do that. I skimmed the code of Heirline once again and I think I found the reason for that. The following code is from module `heirline.highlights`, in function `normalize`.

```lua
local function normalize_hl(hl)
    local fixed_hl = vim.tbl_extend("force", hl, {})
    fixed_hl.foreground = hex(hl.foreground or hl.fg)
    fixed_hl.background = hex(hl.background or hl.bg)
    fixed_hl.special = hex(hl.special or hl.sp or hl.guisp)
    fixed_hl.fg = nil
    fixed_hl.bg = nil
    fixed_hl.sp = nil
    fixed_hl.force = nil
    -- ...
```

As the previous code shows, `fixed_hl` first attempts to set the `foreground` field from the `foreground` field followed by the `fg` field, which means that if both `foreground` and `fg` are set, this function will always prefer the `foreground` field from `hl`. This condition not necessarily leads to a problem. For example, if the user set the status line throught the following code, the foreground color will work as expected.

```lua
require'heirline'.setup{
  provider = 'fuuuuuuuu',
  hl = {fg = '#ff0000', bg = '#007f7f'}
}
```

The problem comes when both `foreground` and `fg` fields are set at the same time, which occurs due to the color merging or inheritance. The following code is from module `heirline.statusline`, in function `Statusline:eval`.

```lua
    -- ...
    local hl = type(self.hl) == "function" and (self:hl() or {}) or self.hl -- self raw hl
    local parent_hl = self:nonlocal("merged_hl")

    if parent_hl.force then
        self.merged_hl = vim.tbl_extend("keep", parent_hl, hl)
    else
        self.merged_hl = vim.tbl_extend("force", parent_hl, hl)
    end
    -- ...
```

As the previous code evidences and according with the rest of the `eval` method, if a status line has children, the highlight definitions will always be merged, which leads to the ambiguity problem involving abbreviated and extended highlight fields.

**Comment by atchim** [comment]
I suggest to take off the extended properties and only allow the abbreviated ones, since they are the ones mentioned in the help for `synIDattr()`. Also, seems that the abbreviated ones take precedence over the extended ones in the function `nvim_set_hl`. It's possible to confirm this behavior through the following snippet.

```lua
vim.api.nvim_set_hl(0, 'Foo', {fg = '#ff0000', foreground = '#00ffff'})
vim.cmd'hi Foo' -- Will have the red foreground color, since `fg` takes precedence over `foreground`.
```

**Comment by rebelot** [comment]
Ideally one should choose only one form, abbreviated or long and keep that consistent. Thanks for pointing out that mixing the two can lead to weird results because of highlight merging. I'll probably lean towards enforcing the contracted form
