### ISSUE TITLE
weird behaviour when switching between buffers

### ISSUE THREAD

**Issue by MurdeRM3L0DY** [rebelot/heirline.nvim#28]
With non-global statusline, when switching between buffers, my vimode component gets updated wrongly in both buffers.

https://user-images.githubusercontent.com/95099980/167689039-c3cfc3c9-3f83-4fb0-970c-4b3d8af8eb15.mp4

**Comment by rebelot** [comment]
This happens because the return value of `vim.fn.mode()` is "global" i.e. it's not possible to have multiple modes in different buffers. I'd suggest removing the `ViMode` component from inactive statuslines (see the cookbook) and guard the terminal vi mode like this

```lua
    local TerminalStatusline = {
        condition = function()
            return conditions.buffer_matches({ buftype = { "terminal" } })
        end,
        { condition = conditions.is_active, ViMode, Space },
        ...
    }
```
If you followed my advice, regarding the `mode_color` function, here's a safer example. I'll soon put this in the cookbook.

```lua
        static = {
            mode_color = function()
                local mode_colors = {
                    n = colors.red,
                    i = colors.green,
                    v = colors.cyan,
                    V = colors.cyan,
                    ["\22"] = colors.cyan, -- this is an actual ^V, type <C-v><C-v> in insert mode
                    c = colors.orange,
                    s = colors.purple,
                    S = colors.purple,
                    ["\19"] = colors.purple, -- this is an actual ^S, type <C-v><C-s> in insert mode
                    R = colors.orange,
                    r = colors.orange,
                    ["!"] = colors.red,
                    t = colors.red,
                }
                local mode = conditions.is_active() and vim.fn.mode() or 'n' -- if not current window, use colors from normal mode
                return mode_colors[mode]
            end,
```

**Comment by MurdeRM3L0DY** [comment]
Yeah I used a similar method to the one you recommended.
https://github.com/MurdeRM3L0DY/dotfiles/blob/207d185b7fc8d0eed843c930693dbeed4b019434/roles/nvim/files/lua/plugins/heirline/config.lua#L41
 I use global statusline but I thought this was a bug on heirline that's why I reported it.
