### ISSUE TITLE
Status line dissapears after saving/resizing window

### ISSUE THREAD

**Issue by richin13** [rebelot/heirline.nvim#30]
## Description

Hello, thanks for this awesome plugin! I'm currently migrating my existing config to this plugin but I'm noticing a weird behavior I cannot identify what the issue with my config.

When I open a brand new file I get a fancy status line:
![image](https://user-images.githubusercontent.com/8370058/170777275-17e8127c-0ef8-4aeb-ab0e-dfb66a82ce0e.png)

As soon as a do any of the following:

* Save the file
* Resize the window
* Open telescope
* Open nvim-tree

My status line is gone forever 😢 
![image](https://user-images.githubusercontent.com/8370058/170777528-58410aa0-cb3c-403b-b075-5afe11a07afd.png)

Here's [a gist with my WIP config](https://gist.github.com/richin13/6907b08b44af4688b851e72b352180e3) but overall I believe I'm just following what's on the cookbook! I load the plugin like this in my `init.vim`, could this be the culprit?

```vim
function! ConfigStatusLine()
  lua require('plugins.heirline').setup()
endfunction

augroup status_line_init
  autocmd!
  autocmd VimEnter * call ConfigStatusLine()
augroup END
```

## Some extra info

```
:version
NVIM v0.8.0-dev+317-ge2940d3c7
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -
DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-pr
ototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-a
ttribute -Wmissing-prototypes -Wimplicit-fallthrough -Wsuggest-attribute=pure -Wsuggest-attribute=
const -Wsuggest-attribute=malloc -Wsuggest-attribute=cold -Wvla -fstack-protector-strong -fno-comm
on -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FL
OAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -
I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/in
clude -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/buil
d/include
Compiled by runner@fv-az216-205

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

`HEAD` -> bb7eaec8f5f8e762b23da91109b54e1b3518c7b8

**Comment by rebelot** [comment]
that's very odd... what's the value of `:set stl?` and `:setlocal stl?` after it disappears? It's possible that something else is overriding the statusline. Alternatively, if it is still set to `%{%v:lua.require.'heirline'.eval_statusline()%}` it's possible that some of your components are gone bananas but that's even stranger.

**Comment by richin13** [comment]
> that's very odd... what's the value of `:set stl?` and `:setlocal stl?` after it disappears? It's possible that something else is overriding the statusline. Alternatively, if it is still set to `%{%v:lua.require.'heirline'.eval_statusline()%}` it's possible that some of your components are gone bananas but that's even stranger.

Hey, thank you for your response. In case anyone bumps into a similar issue: I tried running both `:set stl?` and `:setlocal stl?` and the value was the same:

```
  statusline=%=
```

I looked into what you said: "It's possible that something else is overriding the statusline" and indeed I had `galaxyline.nvim` still installed, removing it fixed the issue 😅 

Thank you so much, this status line plugin is awesome!
