### ISSUE TITLE
Support for adding highlight groups

### ISSUE THREAD

**Issue by siduck** [rebelot/heirline.nvim#32]
Hi! im new to heirline and was going through the docs and couldnt found any option for setting a highlight group for a component 

![image](https://user-images.githubusercontent.com/59060246/171475774-c9ce7394-e30d-47cb-b7e0-9feb5f42e9ad.png)

Feline has that option btw. 

Usage: 

```lua
hl= "Heirline_git"
```

so if the hl's a string then use the highlight group

**Comment by rebelot** [comment]
Give it a shot! :)

**Comment by siduck** [comment]
@rebelot currently i just set up the vimode component and it works bad when the update option is set to it

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/171900325-f544faac-93ee-4728-aee2-a7a69158e242.mp4

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/171900361-09e93954-6e20-4edd-8562-efd5909fd851.png)

Also how do i change the bg color of whole statusline?

**Comment by siduck** [comment]
@rebelot i was unable to change bg color for the surround so i stopped configuring, it'd be nice to add the highlight group support for the surround characters too 

```lua
ViMode = utils.surround({ "", "" }, "my highlight group" , ViMode)
```

**Comment by siduck** [comment]
Also one query.. it'd be nice to have dynamic padding between components or divide the statusline components in 3 components so we dont have to worry about manully adding spaces between components 
```lua
local left = { ... } 
local middle = { ... } 
local  right = { ... } 

local sections = { left , middle , right }
local statusline = {sections}
```

**Comment by rebelot** [comment]
> it'd be nice to add the highlight group support for the surround characters too [...] like if when a highlight group's specified then take bg/fg of hl group for the surround characters

`utils.surround` takes a `string` or `function -> string` as second argument, that's supposed to be a color name or rgb hex code. The reason it cannot support an highlight name is that it's not possible to distinguish between a color name or an highlight group name from its type. However, it's always possible to retrieve colors from highlight groups using `utils.get_highlight`

```lua
ViMode = utils.surround({ "", "" }, utils.get_highlight("my highlight group").fg , ViMode)
```

>Also one query.. it'd be nice to have dynamic padding between components or divide the statusline components in 3 components so we dont have to worry about manully adding spaces between components

Absolutely not. The whole idea behind heirline is that users can do _almost_ anything. This has the drawback that common things are slightly more verbose, however hard things become possible, because no opinionated behavior will stand as an obstacle.

What you are asking can be accomplished like this 

```lua
local align = { provider = "%=" }
local left = { ... } 
local middle = { ... } 
local right = { ... } 

local sections = { left , align, middle, align right }
local statusline = {sections}
```

**Comment by siduck** [comment]
cool.. @rebelot I wanted to set bg for the surround too if possible ;((

**Comment by rebelot** [comment]
What do you mean? The use case is to surround a component with a colored delimiter: the provided color will be used as the _foreground_ of the delimiter and as the _background_ of the surrounded stuff.

Also remember that `utils.surround` is just an utility, you can do everything "manually" if you need more control:

```lua
local mysurroundedcomponent = {
{provider=' <<< ', hl = {...}},
{<your component>},
{provider = '>>>', hl = {...}}
}
```

**Comment by rebelot** [comment]
It looks ugly 'cause it's nonsense, but you get the idea. Also remember that you don't need to use `surround` if it's easier to do it manually..

```lua
    local surrr = {
        utils.surround({ "", "" }, "red", {
            utils.surround({ "", "" }, "green", utils.surround({ "", "" }, "blue", { provider = "heyya" })),
            { provider = "Normal" },
        }),
    }
```
