### ISSUE TITLE
Hide winbar, not empty

### ISSUE THREAD

**Issue by lvim-tech** [rebelot/heirline.nvim#34]
Hello and thanks for the great plugin.
My question: is there a way to prevent winbar from showing for some file types (not empty winbar - provider = "").

Thanks in advance!

**Comment by rebelot** [comment]
Not at the moment unfortunately.. the only way would be to set local winbar for every window except
The ones you don't want it.

https://github.com/neovim/neovim/issues/18660

**Comment by lvim-tech** [comment]
I'm using ctrl-space. My problem is only with this plugin.
Normal view (whitout winbar):
![2](https://user-images.githubusercontent.com/82431193/171981125-5a695927-193d-48e7-abb6-1de480941fe3.png)
With winbar:
![1](https://user-images.githubusercontent.com/82431193/171981167-d99f29bc-eed5-4b88-8269-edef05c5d54e.png)

**Comment by rebelot** [comment]
I don't understand why you reopened the issue. There's nothing that can be done heirline-side. 

Please see the nvim issue. That should explain why it's not possible to remove the winbar on some file types if a global value was set.

Setting a local value to every window except a few ones is feasible, and I have tried this approach, but it's no way clean nor secure.

**Comment by lvim-tech** [comment]
Sorry, @rebelot

**Comment by rebelot** [comment]
@lvim-tech I've just made some changes, after all there was another feasible approach.

Please check out be8d39c33267252f75abeef55987b6c48bf032f0 and see if it suits you.

to disable the winbar on specific buffers/windows see this: https://github.com/rebelot/heirline.nvim/blob/master/cookbook.md#winbar

**Comment by lvim-tech** [comment]
Perfect! Great plugin! Thanks, @rebelot .
