### ISSUE TITLE
Update field doesnt work

### ISSUE THREAD

**Issue by siduck** [rebelot/heirline.nvim#35]
As per the docs, the VIMode component gets updated at the ModeChanged event right?  ![image](https://user-images.githubusercontent.com/59060246/171971258-a23c89d7-43b8-4dc8-911a-a107d5cff25f.png) 

But then my vimode component bugs weirdly, see : 

https://user-images.githubusercontent.com/59060246/171971259-c4eaa85f-5bf4-41a0-b1e0-0ea12e10421a.mp4

**Comment by siduck** [comment]
And the update field in LspStatus component gives me this error 
 
 
![image](https://user-images.githubusercontent.com/59060246/171971334-7b1404c8-8e8e-4d89-81fe-836edd2393e2.png)

![image](https://user-images.githubusercontent.com/59060246/171971339-2c684a4e-f151-473b-a6fe-3fc6cc73d49d.png)

**Comment by rebelot** [comment]
LspAttach and LspDetach were introduced on nightly. 

As per the ViMode component you're right, it seems that for command mode the ModeChange event is fired after the statusline is redrawn. You might just as well remove the update field for now or you can do this:

`au ModeChanged * redrawstatus`

**Comment by siduck** [comment]
thx!
