### ISSUE TITLE
Plugin assumes RGB colors => does not support cterm colors (from 256 color palette)

### ISSUE THREAD

**Issue by bew** [rebelot/heirline.nvim#36]
Hello!

I'm in the process of converting my old nvim config to Lua, and rewriting most of my config.
I've chosen heirline for the statusline, I love what you did with it!

I noticed that the highlighting system assume we're using RGB colors, but in my case I want to only use colors from the 256 color palette.

<details>
<summary>>>> preview of the available colors, from 0 to 255 <<<</summary>

![image](https://user-images.githubusercontent.com/9730330/172061554-a2bcc11a-8e9b-42b8-9a9b-df47386de906.png)
(this palette has been generated using https://github.com/guns/xterm-color-table.vim)

</details>

I actually prefer using these than using RGB colors, because 256 colors are largely enough for me, and RGB actually give to much choice for my taste..

---

FYI highlights in 256 color mode are given using `ctermfg`, `ctermbg` and `cterm` (for the style)
Read more at `:h highlight-args`

I quickly looked at your code, the highlight is created here:
https://github.com/rebelot/heirline.nvim/blob/eab43b39a40e0249b8c93c1f090c1b9e5ca31c49/lua/heirline/highlights.lua#L14
that function does accept `cterm*` params.

I tested this:
```vim
lua vim.api.nvim_set_hl(0, "TestGroup", {cterm={bold = true}, ctermbg=124, ctermfg=255})
hi TestGroup
```
and the output is:
![image](https://user-images.githubusercontent.com/9730330/172062102-fd104c95-217b-4774-b003-91684d7d53b5.png)

:point_right: I think the simplest implementation in heirline would be to accept (and merge them as necessary) the new fields `cterm`, `ctermbg` & `ctermfg` in the `hl` component property.
(the implementation of `name_hl` would also need to take this into account)

What do you think ?

**Comment by rebelot** [comment]
you can use 256 color names (i.e https://www.ditig.com/256-colors-cheat-sheet)

```lua
{
    provider = 'AbraCadabra!',
    hl = { fg = "LightGoldenrod1", bg = "CornflowerBlue"}
}
```

**Comment by bew** [comment]
Interesting but unfortunately no, it doesn't work as it sets the `guifg` & `guibg` fields, not the `¢term*` fields:
![image](https://user-images.githubusercontent.com/9730330/172167358-375204da-8cdf-4237-b50a-aff35fc780ba.png)

And the resulting statusline, if using your example as a statusline:
![image](https://user-images.githubusercontent.com/9730330/172167433-54cea422-725c-4710-8ab9-e11092f9be88.png)

I didn't enabled RGB support in my terminal, and would much prefer to have my tools use 256 terminal colors than RGB ones.
Do you see what I mean?

**Comment by rebelot** [comment]
I see, I thought you only needed a convenient way to indicate 8 bit colors.

I'll think about it.

**Comment by bew** [comment]
Thanks a lot!

I tried using this:
```lua
  require"heirline".setup({
    { provider = "before " },
    {
      provider = "%f",
      hl = { cterm = {italic = true}, ctermfg = 123 },
    },
    { provider = " after" },
  })
```
And I get:
![image](https://user-images.githubusercontent.com/9730330/172372223-92e447a0-5292-48d3-8e83-cbb79833bcca.png)

:point_right: I'd have expected to not have any background colors, and have the same default white everywher.

I'm not sure if the behavior is intended or not.. is it because statusline highlights need to always have a background?
What would be the proper way to fix that if it's intended?

**Comment by rebelot** [comment]
> is it because statusline highlights need to always have a background?

It's not they _need_, it's just the way vim handles highlights, if you don't provide a background color you won't have one. Commonly, one wants some default colors tho, here's an example.

All highlights will be recursively merged, so foreground will be overwritten, but if no background is provided, the default one will be used.

```lua
 require"heirline".setup({
    hl = function()
        if conditions.is_active() then
            return "StatusLine"
        else
            return "StatusLineNC"
        end
    end,
    { provider = "before " },
    {
      provider = "%f",
      hl = { cterm = {italic = true}, ctermfg = 123 },
    },
    { provider = " after" },
  })
```

**Comment by bew** [comment]
Thanks a lot!

As for the weird black background, it was actually an issue with my theme.. I really have no idea why I had soo many `cterm=reverse` in it.. it messes up everything!! (now I have 0 left ^^)

Thanks a lot again for the examples and the plugin, it's great \o/
