### ISSUE TITLE
How do I completely disable heirline winbar for some filetypes?

### ISSUE THREAD

**Issue by MordechaiHadad** [rebelot/heirline.nvim#40]
I have this code:
```lua
local winbar = {
        condition = function()
            return conditions.buffer_matches({ filetype = { "toggleterm", "Trouble" } }) == false
        end,
        BufferComponent,
        ExplorerComponent,
        Navic,
    }
 ```
 which kinda works? here is an example(I highlighted the window separator for better visibility):
 ![](https://p0rn.pro/ACourageousAndCulturedAttempt)
 There is empty space between the Window Separator and the Window content itself which indicates that a winbar is meant to go there.

**Comment by rebelot** [comment]
See instructions at https://github.com/rebelot/heirline.nvim/blob/master/cookbook.md#winbar

**Comment by rebelot** [comment]
Just a note, if you prefer using an autocmd, to remove winbar for terminals you need a TermOpen autocmd

**Comment by MordechaiHadad** [comment]
@rebelot oh so I need to add an autocmd + the winbar conditions?

**Comment by MordechaiHadad** [comment]
@rebelot thank you!
