### ISSUE TITLE
Colors are not working

### ISSUE THREAD

**Issue by cjnucette** [rebelot/heirline.nvim#41]
Since two updates ago this plugin is showing the wrong colors.

I've disabled all my plugins with the exception of `colorscheme` and `heirline`. I copied and pasted the following from the cookbook:

        local conditions = require("heirline.conditions")
        local utils = require("heirline.utils")
        
        local colors = {
          bright_bg = utils.get_highlight("Folded").bg,
          red = utils.get_highlight("DiagnosticError").fg,
          dark_red = utils.get_highlight("DiffDelete").bg,
          green = utils.get_highlight("String").fg,
          blue = utils.get_highlight("Function").fg,
          gray = utils.get_highlight("NonText").fg,
          orange = utils.get_highlight("Constant").fg,
          purple = utils.get_highlight("Statement").fg,
          cyan = utils.get_highlight("Special").fg,
          diag_warn = utils.get_highlight("DiagnosticWarn").fg,
          diag_error = utils.get_highlight("DiagnosticError").fg,
          diag_hint = utils.get_highlight("DiagnosticHint").fg,
          diag_info = utils.get_highlight("DiagnosticInfo").fg,
          git_del = utils.get_highlight("DiffDelete").fg,
          git_add = utils.get_highlight("DiffAdd").fg,
          git_change = utils.get_highlight("DiffChange").fg,
        }
        
        require('heirline').load_colors(colors)
        
        local ViMode = {
          -- get vim current mode, this information will be required by the provider
          -- and the highlight functions, so we compute it only once per component
          -- evaluation and store it as a component attribute
          init = function(self)
            self.mode = vim.fn.mode(1) -- :h mode()
        
            -- execute this only once, this is required if you want the ViMode
            -- component to be updated on operator pending mode
            if not self.once then
              vim.api.nvim_create_autocmd("ModeChanged", { command = 'redrawstatus' })
              self.once = true
            end
          end,
          -- Now we define some dictionaries to map the output of mode() to the
          -- corresponding string and color. We can put these into `static` to compute
          -- them at initialisation time.
          static = {
            mode_names = { -- change the strings if you like it vvvvverbose!
              n = "N",
              no = "N?",
              nov = "N?",
              noV = "N?",
              ["no\22"] = "N?",
              niI = "Ni",
              niR = "Nr",
              niV = "Nv",
              nt = "Nt",
              v = "V",
              vs = "Vs",
              V = "V_",
              Vs = "Vs",
              ["\22"] = "^V",
              ["\22s"] = "^V",
              s = "S",
              S = "S_",
              ["\19"] = "^S",
              i = "I",
              ic = "Ic",
              ix = "Ix",
              R = "R",
              Rc = "Rc",
              Rx = "Rx",
              Rv = "Rv",
              Rvc = "Rv",
              Rvx = "Rv",
              c = "C",
              cv = "Ex",
              r = "...",
              rm = "M",
              ["r?"] = "?",
              ["!"] = "!",
              t = "T",
            },
            mode_colors = {
              n = "red",
              i = "green",
              v = "cyan",
              V = "cyan",
              ["\22"] = "cyan",
              c = "orange",
              s = "purple",
              S = "purple",
              ["\19"] = "purple",
              R = "orange",
              r = "orange",
              ["!"] = "red",
              t = "red",
            }
          },
          -- We can now access the value of mode() that, by now, would have been
          -- computed by `init()` and use it to index our strings dictionary.
          -- note how `static` fields become just regular attributes once the
          -- component is instantiated.
          -- To be extra meticulous, we can also add some vim statusline syntax to
          -- control the padding and make sure our string is always at least 2
          -- characters long. Plus a nice Icon.
          provider = function(self)
            return " %2(" .. self.mode_names[self.mode] .. "%)"
          end,
          -- Same goes for the highlight. Now the foreground will change according to the current mode.
          hl = function(self)
            local mode = self.mode:sub(1, 1) -- get only the first mode character
            return { fg = self.mode_colors[mode], bold = true, }
          end,
          -- Re-evaluate the component only on ModeChanged event!
          -- This is not required in any way, but it's there, and it's a small
          -- performance improvement.
          update = 'ModeChanged'
        }
        
        local Align = { provider = "%=" }
        local Space = { provider = " " }
        
        local DefaultStatusline = {
          ViMode, Space, Align
        }
        
        local InactiveStatusline = {
          condition = function()
            return not conditions.is_active()
          end,
        
          ViMode, Space, Align
        }
        
        local StatusLines = {
        
          hl = function()
            if conditions.is_active() then
              return "StatusLine"
            else
              return "StatusLineNC"
            end
          end,
        
          init = utils.pick_child_on_condition,
        
          InactiveStatusline, DefaultStatusline,
        }
        
        require("heirline").setup(StatusLines)

And this is the result:

![image](https://user-images.githubusercontent.com/2278326/173888278-fa9f6c09-41f9-48fe-9d0c-6e3c56336fd8.png)

This is with my regular configuration:

![image](https://user-images.githubusercontent.com/2278326/173888529-639a4e20-a15b-4e71-8fa1-dd9ce0d2a353.png)

By the way, you have a typo with some highlight group names: `diffDeleted` should be `DiffDelete`, same with add and change.

**Comment by rebelot** [comment]
I think your `StatusLine` hl group has `reverse` in it. You can change it or use `get_highlight` as before.

`diffDeleted` is a common hl group controlling the foreground Git differences. `DiffDelete` is a default group controlling (usually) the background of deleted lines in diff mode

**Comment by cjnucette** [comment]
No, I couldn't but it can be closed.
