### ISSUE TITLE
inconsistent highlights

### ISSUE THREAD

**Issue by MurdeRM3L0DY** [rebelot/heirline.nvim#45]
Ever since this commit https://github.com/rebelot/heirline.nvim/commit/60d92a6f8003c5f56fd521fbe9fec43c0c9b4d94, I've been having inconsistent behaviour with highlights when I launch neovim.

Notice the statusline and winbar are dimmed in this image
![2022-07-13_12-30](https://user-images.githubusercontent.com/95099980/178713870-c3cc5c9f-d043-4ac3-b47d-57e0c48739d9.png)
and not in this one
![2022-07-13_12-32](https://user-images.githubusercontent.com/95099980/178714058-79171846-0344-4865-b64f-5287306ba2c3.png)

**Comment by rebelot** [comment]
I am sorry but I need more context to help you. How do you specify the fg/bg colors of the statusline? Please see the latest updates to the cookbook for best practices on colors setup.

**Comment by MurdeRM3L0DY** [comment]
I think this happened because, as there's no load order when it comes to neovim plugins, heirline (which depends on colors from my colorscheme plugin) would load before my colorscheme plugin. I've fixed it by forcing heirline to load after my colorscheme.
