### ISSUE TITLE
Timer-based update to components

### ISSUE THREAD

**Issue by DrKGD** [rebelot/heirline.nvim#48]
From the documentation for `update` key in component:
```Description: Control when the component should be updated or return a per-window cached value. If update is a function, the component will be updated whenever the function return value is true; else, a string or a table of strings will be interpreted as autocommand event names that should trigger the component evaluation.```

As I am trying to add some animated text components (e.g. a carousel with unnecessary file information such as `file_encoding, file_size, file_format`), I have the following questions
1. Is it possible to use a `vim.wait` call or similiar to update component exactly after, let's say, `300ms`? 
I'd prefer a passive wait over an active one.
2. Any reason not to allow User defined autocmd, such as `update = 'User MyUpdateEvent'`, where `MyUpdateEvent` is manually fired (either by a `vim.defer_fn` infinite loop [timer](https://github.com/alex-popov-tech/timer.nvim) or the user itself)?

My understanding is that at the moment `User` autocmd are captured, but the pattern which they are using is ignored.
More specifically
```lua
local mre = {
  static = {
    value = 1
  },

  update = 'User MyUpdateEvent',

  init = function(self)
    self.value = self.value + 1
  end,

  provider = function(self)
    return tostring(self.value)
  end
}

require('heirline').setup({ mre })
```

Then it does not matter which User autocmd we are using: they will both result in an increment of `self.value` 
```lua
vim.api.nvim_exec_autocmds("User", { pattern = "MyUpdateEvent" })
vim.api.nvim_exec_autocmds("User", { pattern = "NotTheDesiredEvent" })
```

Thanks in advance!

**Comment by rebelot** [comment]
Yes, with the current implementation there's no handling of patterns but it sounds reasonable to implement that.

for timers, I think it can be a bit tricky... but I think that user autocommands should be sufficient. What do you think?

**Comment by rebelot** [comment]
can you try d2767b3678069a5be31f0783b5309016f4720d59 ?

**Comment by DrKGD** [comment]
Seems to be working, am I using it as you would expect?
```lua
local mre = {
  static = {
    value = 1
  },

  update = {'User', pattern = 'MyUpdateEvent'},

  init = function(self)
    self.value = self.value + 1
  end,

  provider = function(self)
    return tostring(self.value)
  end
}

require('heirline').setup({ mre })
```

Then
```lua
-- This increments the value
vim.api.nvim_exec_autocmds("User", { pattern = "MyUpdateEvent" })
-- This does not
vim.api.nvim_exec_autocmds("User", { pattern = "NotTheDesiredEvent" })
```

About timers... yeah, totally. Not really a big deal, either them or this way is nice!

**Comment by rebelot** [comment]
Yes! I'll update the docs soon!
