### ISSUE TITLE
heirline, wilder and winbar

### ISSUE THREAD

**Issue by DrKGD** [rebelot/heirline.nvim#49]
Any winbar configuration made through heirline throws error ```E36: Not enough room``` on any second [wilder](https://github.com/gelguy/wilder.nvim/)  prompt(s).

```
E5555: API call: Vim(append):Error executing lua callback: vim/_meta.lua:0: Vim:E36: Not enough room
stack traceback:
        [C]: in function 'nvim_set_option_value'
        vim/_meta.lua: in function '_set'
        vim/_meta.lua: in function '__newindex'
       ...te/pack/packer/start/heirline.nvim/lua/heirline/init.lua:28: in function <...te/pack/packer/start/heirline.nvim/lua/heirline/init.lua:27>
```

Any manual, global configuration, however, does not trigger aforementioned error.
```lua
-- Any statusline configuration, no winbar configuration
require('heirline').setup( ...  , nil )

vim.opt.winbar='%f'
-- or set winbar=%f
```

MRE (with packer)
```lua
-- Basic wilder configuration
use { "gelguy/wilder.nvim",
	event = 'CmdlineEnter',  -- Lazy loading on CmdlineEnter 
	config = function()
		local w = require('wilder')
		w.setup({modes = { '/', '?', ':'}})
	end }

use { "rebelot/heirline.nvim",
	config = function()
		require('heirline').setup({}, { provider = 'test'})
	end },
```

**Comment by DrKGD** [comment]
I suppose wilder creates a new buffer, along the lines of `Wilder Popup %d` and its buftype is `nofile` (from [wilder vim_api.vim](https://github.com/gelguy/wilder.nvim/blob/master/autoload/wilder/renderer/vim_api.vim#L60))
```vim
...
let l:buf = bufadd('[Wilder Popup ' . s:index . ']')
call bufload(l:buf)
call setbufvar(l:buf, '&buftype', 'nofile')
...
```

Thus I tried ignoring all nofile buffers in the winbar with no success
```lua
local bar = {
	condition = function()
		return not require('heirline.conditions').buffer_matches({
			buftype = { "nofile" },
		})
	end,

	provider = '%f'
}

require('heirline').setup({}, bar)
```

Am I missing something here?

**Comment by rebelot** [comment]
are you on latest nightly? https://github.com/neovim/neovim/issues/19458 introduced several bugs when using local winbar. Please see https://github.com/rebelot/heirline.nvim/issues/47#issuecomment-1211815471 for a temporary fix

**Comment by DrKGD** [comment]
Damn, totally missed that ... thanks for the quick fix!

**Comment by rebelot** [comment]
related https://github.com/neovim/neovim/issues/19464
