### ISSUE TITLE
Set background for blocks in not current window

### ISSUE THREAD

**Issue by catgoose** [rebelot/heirline.nvim#50]
I tried using WinbarNC to set background for winbar not current window, but the configured blocks are unaffected. Is there a way to determine if a window is not current so I can pass a function to the bg member of the hl table?

Thanks.

**Comment by rebelot** [comment]
I'd recommend you to take a look at the [cookbook](https://github.com/rebelot/heirline.nvim/blob/master/cookbook.md).

```lua
conditions = require'heirline'.conditions

winbar = {
  provider = "%f",
  hl = function()
    if conditions.is_active() then
      return 'WinBar'
    else
      return 'WinBarNC'
    end
  end
}

**Comment by max397574** [comment]
ig you could close this then @rebelot
