### ISSUE TITLE
bug: bad argument to ipairs

### ISSUE THREAD

**Issue by max397574** [rebelot/heirline.nvim#53]
it looks like there was a breaking change somewhen that broke my winbar when I open neovim with out a file (just `nvim` in terminal)
I unfortunately don't have much time to debug it
only thing I can say is that the error is that here:
https://github.com/rebelot/heirline.nvim/blob/489aa37a6aec30c43217bd4ddc75ef9f945c9d0d/lua/heirline/statusline.lua#L323-L323
`tree` is nil
my config:
https://github.com/max397574/omega-nvim/blob/3bacaac462dc7c6ccb672b92d3c9f7889e0a640d/lua/omega/modules/ui/heirline.lua#L133-L348

this is the complete error:
```
E5108: Error executing lua ...k/packer/start/heirline.nvim/lua/heirline/statusline.lua:323: bad argument #1 to 'ipa
irs' (table expected, got nil)                                                                                     
stack traceback:                                                                                                   
        [C]: in function 'ipairs'                                                                                  
        ...k/packer/start/heirline.nvim/lua/heirline/statusline.lua:323: in function 'eval'                        
        ...te/pack/packer/start/heirline.nvim/lua/heirline/init.lua:72: in function <...te/pack/packer/start/heirli
ne.nvim/lua/heirline/init.lua:69>
```

**Comment by rebelot** [comment]
should be fixed, sorry for the inconvenience!
