### ISSUE TITLE
Show all buffers after session is restored

### ISSUE THREAD

**Issue by lostl1ght** [rebelot/heirline.nvim#59]
### Discussed in https://github.com/rebelot/heirline.nvim/discussions/57

<div type='discussions-op-text'>

<sup>Originally posted by **lostl1ght** September  5, 2022</sup>
Hi, thanks for the plugin.

I've followed the cookbook on the tabline setup.
However, when I'm restoring a session only the last active buffer is shown in a tabline.
Is there a way to render all opened buffers on startup?</div>

It seems like `make_buflist` has to render all opened buffers but it does not.
I am using [auto-session](https://github.com/rmagatti/auto-session) as a session manager.

<details>
  <summary>Minimal config</summary>

  ```lua
  local TablineFileName = {
    provider = function(self)
      local filename = self.filename
      filename = filename == '' and '[No Name]' or vim.fn.fnamemodify(filename, ':t')
      return filename .. ' '
    end,
  }

  local TablineFileNameBlock = {
    init = function(self)
      self.filename = vim.api.nvim_buf_get_name(self.bufnr)
    end,
    TablineFileName,
  }


  local TablineBufferBlock = {
    TablineFileNameBlock,
  }

  local utils = require('heirline.utils')
  local BufferLine = utils.make_buflist(
    TablineBufferBlock
  )

  local tabline = { BufferLine }

  require('heirline').setup(nil, nil, tabline)
  vim.cmd([[au FileType * if index(['wipe', 'delete', 'unload'], &bufhidden) >= 0 | set nobuflisted | endif]])
  ```

**Comment by lostl1ght** [comment]
I figured it out.
I had to modify `get_bufs` function to get the desired behaviour like that:
```lua
local function get_bufs()
    return vim.tbl_filter(function(bufnr)
        return vim.bo[bufnr].buflisted
    end, vim.api.nvim_list_bufs())
end
```
Then I passed it into `make_buflist`.

Please, close the issue if I made everything clear.

**Comment by rebelot** [comment]
Mmh good job! Also I think listing unloaded buffers is a nicer default, as bnext and bprev would still reach unloaded buffers. Maybe I could add to the bufname component example a check to render differently unloaded buffers

**Comment by lostl1ght** [comment]
I think a default you describe is definitely nicer as I was really confused why unloaded buffers did not show up but as I `bn` and `bp` trough they did.

Speaking of the example, I'm not sure what do you mean by 'differently unloaded buffers'.

**Comment by rebelot** [comment]
Something like in the file flags component a new branch that if buffer is unloaded a little grayed downward arrow is added at the end of the file name

**Comment by lostl1ght** [comment]
Ah, I see.

I achieve that with colors:
```lua
local TablineFileNameBlock = {
-- code
  hl =  = function(self)
    if self.is_active then
      return { fg = orange }
    elseif self.is_visible then
      return { fg = blue }
    else
      return { fg = gray }
    end
  end,

-- code
}
```

**Comment by lostl1ght** [comment]
It looks like that:
![image](https://user-images.githubusercontent.com/61948252/188664490-0ef9fabb-0a84-4c4d-8d58-fa4d9def975b.png)

I have 2 buffers in a window, my cursor is inside orange buffer, blue buffer is visible and gray is unloaded.
Choice of colors is debatable but it works.
