### ISSUE TITLE
Avail is shared between statusline instances

### ISSUE THREAD

**Issue by arsham** [rebelot/heirline.nvim#6]
In case of window splits, it is not possible to determine whether the current buffer's statusline has enough room.

**Comment by rebelot** [comment]
should be fixed, checkout c5ab7d6bdcfb9f0f83373ad922dfd95dde8059f3

now you should call `require'heirline'.get_available_space(0)` to get the avail space for the current window. I'm surprised it was so simple. I'm heads up for bugs.

**Comment by rebelot** [comment]
In the meantime, I figured the calculation is not correct, as icons take up more than 1 character

**Comment by rebelot** [comment]
last problem: non-current statuslines will hang with their last value before the window was changed. I haven't come up with anything better than `au CursorHold * let &ro=&ro` to force the refresh yet

**Comment by arsham** [comment]
Thanks for the update. I wouldn't worry about the inactive windows. It would be still a valid state if they are one cycle behind.

1. User's focus is usually on the active window.
2. Changes to the available size is usually required when window is resized.
3. Less often a dynamic widget like LSP related stuff are changing the content. In that case, your attention is mostly on the new content and not the truncated text.
4. Until a few users request for higher resolution updates, I think it is better to avoid the `CursorHold` event.
5. Or it can be a configurable event.

What do you reckon?

**Comment by arsham** [comment]
Hmmm, been trying to utilise the new function and I realised this might not work, specially if two widgets are using this value to truncate themselves. The problem is that the available space is different before and after truncating the text.

**Comment by rebelot** [comment]
I don't have much time atm, could you please provide a minimal example for testing?

**Comment by rebelot** [comment]
I think I have the solution. We need to:

In the eval function

1) reset avail for current window to max window size
2) perform a dummy evaluation of the statusline (all providers will expand to long)
3) get its length
4) update the avail with statusline length
5) re-evaluate the statusline and return it (providers will conditionally expand to short)

Is it efficient? No. Still evaluation time is so small that timing with os.time() still returns 0

**Comment by arsham** [comment]
Here is a working example to illustrate the problem:

```lua
local segment = {
  provider = function()
    if require("heirline").get_available_space(0) < 1 then
      return "1 2 3 4"
    end
    return "1 2 3 4 5 6 7 8 9 A B C D E F G H I J K"
  end,
}
status_line = {
  segment,
  { provider = "%=" },
  segment,
  { provider = "%=" },
  segment,
  { provider = "%=" },
}

require("heirline").setup(status_line)
```

**Comment by rebelot** [comment]
I think we're almost there

![heirline_test](https://user-images.githubusercontent.com/36300441/149638599-119efb52-f939-4ede-aeb6-0bb2b5708228.gif)

**Comment by arsham** [comment]
This is the behaviour I get:

![1](https://user-images.githubusercontent.com/428611/149642760-3ddd70e8-003c-40dd-826b-dc240c7435ea.gif)

**Comment by rebelot** [comment]
I haven't pushed yet

**Comment by rebelot** [comment]
@arsham can you please play a bit with 90b2ae77f26b1b42c3f2ca427bbef12ee6a2a96a and tell me what you think of it? thanks!

**Comment by rebelot** [comment]
One quirk is that if you use expressions like `%-04.8` the minimum avail space will increase. I have something in mind to fix that, but for the moment it should work

**Comment by arsham** [comment]
It's much better. However I don't think it's going to scale:
![2](https://user-images.githubusercontent.com/428611/149657329-b92cde26-4d46-4cd0-9654-a18192503912.gif)

Considering this feature is going to be tricky and probably hard to manage from the users' perspective, I would like to recommend a new direction.

Please note that this idea adds complexity to the logic and I think one of your plugin's strengths is its simplicity. So, I already regret this!

The idea is for users to provide two pieces of information:

1. The priority of the segment: the order in which they shrink
2. A list of gradually degrading quality

Example:
```lua
{
  priority = 4,
  provider = {
    function()
      return string.rep("A", 20)
    end,
    string.rep("A", 10),
    "AAA",
  }
}
```

Now internally when evaluating, the plugin can check the available space, and if there is none, can find the next low priority segment and return its next provider, unless it has reach the end of the list.

I was playing around with this feature to figure out a good compromise and how to incorporate priorities just like feline does. I did a very simple test and it was kind of ok:

```lua
local _priorities = {}
local function priority()
  return _priorities[vim.fn.bufnr()] or 0
end
local function set_priority(n)
  _priorities[vim.fn.bufnr()] = n
end

{
  condition = function()
    return vim.wo.foldenable and priority() > 6
  end,
}

{
    condition = function(self)
      return priority() < 3
    end
}

local priority_check = {
  condition = function()
    local avail = require("heirline").get_available_space(0)
    local p = priority()
    if avail > 1 then
      set_priority(p + 1)
    else
      set_priority(p - 1)
    end

    if p < 0 then
      set_priority(0)
    elseif p > 10 then
      set_priority(10)
    end
  end,
}

local status_line = {
  stop_at_first = true,
  priority_check,
  disabled_buffers,
  active_status_line,
} 
```

During the setup phase a priority list can be made to make the look up easier.

**Comment by rebelot** [comment]
I will think about priorities. Your thoughts are correct:

>Please note that this idea adds complexity to the logic and I think one of your plugin's strengths is its simplicity. So, I already regret this!

this *is not* feline.

Think as if I was providing you some Lego blocks, so that you can build a train, a spaceship, a house, whatever. If there's something useful that cannot be achieved with reasonable ease then I will consider implementing that "upstream" in the most minimal way and provide some utilities/documentation to customize and expand on it.

I prefer "simple things easy and complex things possible", rather than "simple and complex things I've thought of easy, others impossible"

**Comment by rebelot** [comment]
Update:

left and right providers have priority = 1
middle provider has priority = 2

lowest priority: first to contract, last to expand
highest priority: last to contract, first to expand

https://user-images.githubusercontent.com/36300441/150369167-f143eff9-6d28-4ce6-9233-ba53d8f34fcf.mov

All is built on top of the existing core, shouldn't be any breaking change to implement this. I'm still testing some optimizations. My idea is to provide some utilities to wrap a standard component and return a rubber version of it with multiple providers with decreasing length.

1) get a list of rubber providers
1) defer elastic providers (they won't produce output)
1) avail = window_width - statusline_len (this requires raw evaluation of the statusline)
1) now evaluate the elastic providers separately:
1) if they fit, undefer the providers and let the statusline evaluate
1) else, increase their provider index (that selects the output function) in order of priority
1) goto (4)

**Comment by arsham** [comment]
Thanks for the info. I am happy if you would want to close this in favour of #13 .
