### ISSUE TITLE
Invalid reset of `_win_cache` for statuslines

### ISSUE THREAD

**Issue by jonatan-branting** [rebelot/heirline.nvim#63]
Due to a typo in the code, the `_win_cache` attribute is not properly reset if `update` is a function.

https://github.com/rebelot/heirline.nvim/blob/8a8d66122ed05a47910b470ec3361258f6938798/lua/heirline/statusline.lua#L270
(note the `win_cahe` spelling!)

This (unsurprisingly) causes `update` to not function at all if it is a function.

**Comment by rebelot** [comment]
Thanks a lot for debugging this, sorry for the inconvenience. Fixing ASAP.
