### ISSUE TITLE
Only show buffer list when there's more than one listed buffer?

### ISSUE THREAD

**Issue by Barbaross93** [rebelot/heirline.nvim#64]
Hi @rebelot,

Thank you so much for sharing this plugin! It's absolutely fantastic.

One of the last things I'm trying to work out and can't get quite right is to only show the buffer list when there is more than one _listed_ buffer. So far, I have this snippet (which is mostly from the cookbook):
```
local Bufferline = {
    condition = function()
        return #vim.api.nvim_list_bufs() >= 2
    end,
    utils.make_buflist(
        TablineBufferBlock,
        { provider = "", hl = { fg = "gray" } }, -- left truncation, optional (defaults to "<")
        { provider = "", hl = { fg = "gray" } }-- right trunctation, also optional (defaults to ">")
    -- by the way, open a lot of buffers and try clicking them ;)
    )
}
```
This doesn't work unless I change the value `2` to `4`, and presumably this is because `#vim.api.nvim_list_bufs()` returns all buffers and not just the listed ones.

Is there a simple way of getting the number of just the listed buffers?

**Comment by rebelot** [comment]
Can you try this?

```lua
local buf_cache = {}
local buflist = {
    condition = function()
        return buf_cache and #buf_cache > 1
    end,
    utils.make_buflist(bufcomp,ltrunc,rtrunc, nil, buf_cache) -- last argument
}
```

**Comment by Barbaross93** [comment]
Unfortunately, nothing shows at all :(

**Comment by rebelot** [comment]
ok, sorry, my previous example was untested and retrospectively impossible... anyway, this works for me

```lua
local function get_bufs()
    local bufs =  vim.tbl_filter(function(bufnr)
        return vim.api.nvim_buf_get_option(bufnr, "buflisted")
    end, vim.api.nvim_list_bufs())
    return #bufs > 1 and bufs or {}
end

local BufferLine = utils.make_buflist(
    TablineBufferBlock,
    { provider = "", hl = { fg = "gray" } },
    { provider = "", hl = { fg = "gray" } }, get_bufs
)
```

**Comment by Barbaross93** [comment]
Brilliant, that works.

Thank you so much!
