### ISSUE TITLE
Errors on parsing elixir matches with maps

### ISSUE THREAD

**Issue by cfbender** [rebelot/heirline.nvim#68]
### Environment

On neovim 0.8 and latest heirline

When looking at at file that contains some elixir map in a match for a  function declaration:

```elixir
def test(%{"test" => test}) do
	test
end
````

I get an error:
```
E15: Invalid expression: "test" => test
```

This also happens with something like
```elixir
def test(%{test: test}) do
	test
end
````

where I get: 
```
E121: Undefined variable: test
```

and when I hammer it enough it comes out as this:
![image](https://user-images.githubusercontent.com/50554676/194111949-60516c01-a392-43c1-a593-e005e36ba0fb.png)

(excuse the screenshot, it's all I could grab of the issue

I originally thought this was an elixir-ls problem - but now it seems with that error that it stems from the `_eval` call from this plugin. I am still not sure it's _not_ which-key? but it seems like the trace just shows that as being it's re-render function.

Thanks so much for the help!

**Comment by rebelot** [comment]
That syntax is potentially able to be interpreted as a statusline format string and vim would try to execute whatever is inside `%{ }` as a vim expression. This is a problem if you had any provider returning the content of the current line. To prevent it, you need to make the output of such provider safe by substituting `%` with `%%`

**Comment by cfbender** [comment]
Thank you for the quick response! it seems to be an issue with the [AstroNvim heirline config](https://github.com/AstroNvim/AstroNvim/blob/nightly/lua/core/utils/status.lua) then. I can try to track down the issue and open a PR/issue there

**Comment by rebelot** [comment]
Glad to help, also thanks for bringing to my attention that AstroNVim uses heirline ;)

**Comment by cfbender** [comment]
No problem! I think I narrowed it down to [this provider](https://github.com/AstroNvim/AstroNvim/blob/de74668d9e56b217a3908a8111fc6a81835b7ea7/lua/core/utils/status.lua?rgh-link-date=2022-10-05T16%3A46%3A33Z#L94), though I can't figure out why.

I think I will just open an issue there, and disable it locally for myself for now. Thanks again!

**Comment by rebelot** [comment]
```
--- { provider = d.name }, -- add symbol name
+++ { provider = string.gsub(d.name, "%%", "%%%%")
```

**Comment by mehalter** [comment]
Thanks so much for looking at this @rebelot ! I will test out the change you have shared !

Yeah AstroNvim has been getting ready to migrate to using Heirline as the statusline. It will be in the stable release we are making on Friday for AstroNvim v2.0. Great work on this plugin it is super great and very fast and has allowed us to build a great API for letting users easily customize the statusline in Heirline quite nicely. If you are curious, here are our new docs for customizing the statusline in AstroNvim with heirline and our status module: https://astronvim.github.io/nightly/Recipes/status

**Comment by rebelot** [comment]
great project! keep an eye on the cookbook for updates ;)

**Comment by rebelot** [comment]
@mehalter You might want to check out updates on [navic component](https://github.com/rebelot/heirline.nvim/blob/a9b1d883a15f86caf6be76fc646744817d03ef34/cookbook.md?plain=1#L782) for multi-window support and better logic for clickable elements (does not pollute global namespace with redundant functions)
Converting it to work with aerial should be straightforward.

**Comment by mehalter** [comment]
Thanks for the recommendation @rebelot ! Definitely super interested in improving the clickable implementation. I'll check out their implementation to help improve ours. I do want to continue using Aerial as the location engine mainly because it supports getting the location from more sources from just the LSP like if I just have treesitter running for example I can still get breadcrumbs for that. Also we are using Aerial already for having a symbol browser so not needing to rely on another plugin to get location when we have another plugin already calculating symbols as well. Hopefully that explanation is clear 😂 but will definitely check out the navic codebase to see how they are building the clickable elements

**Comment by mehalter** [comment]
Checked out the code in the codebook and it looks great! Thanks so much for this, will definitely update our component in AstroNvim with this implementation!
