### ISSUE TITLE
Error in the docs for static in diagnostics

### ISSUE THREAD

**Issue by JSteitz** [rebelot/heirline.nvim#7]
You are using static in the example for diagnostics.
```
static = {
        error_icon = vim.fn.sign_getdefined("DiagnosticSignError")[1].text,
        warn_icon = vim.fn.sign_getdefined("DiagnosticSignWarn")[1].text,
        info_icon = vim.fn.sign_getdefined("DiagnosticSignInfo")[1].text,
        hint_icon = vim.fn.sign_getdefined("DiagnosticSignHint")[1].text,
    },
```
But if you start with a buffer that does not contain diagnostics, then the static variables will always be nil.
So, you have to move them either into `init` or `provider` :)

**Comment by rebelot** [comment]
Sorry but I don't think that's how it works. It works as expected (even on new buffers) for me. `static` expression are evaluated by lua as it goes through your configuration, even before calling `setup`. I only assume that diagnostic symbols are defined somewhere *before* heirline config is sourced. Their existence has nothing to do with the buffer.

**Comment by JSteitz** [comment]
From the docs for sign_getdefined: `Returns an empty List if there are no signs and when {name} is
		not found.`
This happens definitely if you open vim without parameters.

**Comment by rebelot** [comment]
Can you please provide a minimal working example? Again, that function requires the symbols to be defined, not actually displayed in the buffer.

**Comment by JSteitz** [comment]
Ok, I found the error, somehow my statusbar was really loaded after defining the signs.
I'm sorry for troubling you so much, and thanks for the patience.

**Comment by RoryNesbitt** [comment]
Hey I'm having this exact error. Can you clarify what you did to fix it?

**Comment by JSteitz** [comment]
> ~Hey I'm having this exact error. Can you clarify what you did to fix it?~ Okay adding `after = 'vim-devicons',` to packer seems to have fixed it

Yeah, had to look at the compiled packer scripts too see it.
