### ISSUE TITLE
`update` with multiple autocmd events

### ISSUE THREAD

**Issue by mehalter** [rebelot/heirline.nvim#71]
There are a lot of times when it is useful to update a component on multiple autocmd events. This can be seen with the diagnostics for example doing `update = { "DiagnosticChanged", "BufEnter" },` This works great if you are setting up a single autocmd with a single callback and pattern. This breaks down for example if you want to do the same with git difference component for example. where I want it to be updated on `{ "User", pattern = "GitSignsUpdate" }` and `{ "BufEnter" }`. If you do `{ "User", "BufEnter", pattern = "GitSignsUpdate" }` then you are saying the pattern applies to both autocmd events. Do you think there could be a way to do this where you can create multiple autocommands to update the item?

**Comment by rebelot** [comment]
I've just had something similar in the [discussion](https://github.com/rebelot/heirline.nvim/discussions/70#discussioncomment-3832646)

This is how one could define independent autocommand hooks:

```lua
local Updater = {
  init = function(self)
    if not rawget(self, "once") then
      vim.api.nvim_create_autocomd("Event1", {
        callback = function(args)
          self._win_cache = nil
        end
        })
      vim.api.nvim_create_autocomd("Event2", {
        callback = function(args)
          self._win_cache = nil
        end
        })
    self.once = true
    end
}
```

any children of the above component would be updated on `Event1` or `Event2`. The window-local cache of the component is invalidate by the line `self._win_cache = nil`

I could add this example to the cookbook or allow the update field to be a list of events, but this would probably result in a breaking change

**Comment by mehalter** [comment]
Awesome! Totally understand the avoidance of breaking changes and greatly greatly appreciate the desire to avoid them! I was able to make a generalized `init` function for the AstroNvim status API that resolves my issues and lets me migrate the rest of our statusline components to being updated on demand rather than on intervals (outside of file information component which I haven't quite cracked yet)

**Comment by mehalter** [comment]
sorry for the duplicate issue, I'll make sure to check the discussions before opening anything else!

**Comment by rebelot** [comment]
Oh not a problem at all! I was just pointing out a coincidence ;)

**Comment by rebelot** [comment]
> (outside of file information component which I haven't quite cracked yet)

Maybe I can help, what would you like to achieve? I'd imagine a filetype/bufname/fileflags component that updates on some events?

**Comment by Iron-E** [comment]
> Maybe I can help, what would you like to achieve? I'd imagine a filetype/bufname/fileflags component that updates on some events?

I know I'm not OP, but I just tried this and ended up here:

```lua
update = {'BufEnter', {'User', pattern = 'GitSignsUpdate'}},
```

It's part of a Git component that I'd like to refresh when the git status changes, or when entering a new buffer.

For now I've worked around this by doing something like this:

```lua
local command = 'doautocmd User BufEnterOrGitSignsUpdate'
vim.api.nvim_create_autocmd('User', {command = command, pattern = 'GitSignsUpdate'})
vim.api.nvim_create_autocmd('BufEnter', {command = command})
```

And then set `update` to be on `BufEnterOrGitSignsUpdate`
