### ISSUE TITLE
`showtabline` is hardcoded

### ISSUE THREAD

**Issue by gegoune** [rebelot/heirline.nvim#73]
What an amazing plugin, thank you! My status line never been so cool before.

To the business, I only want to show tabpages on the tabline as per https://github.com/rebelot/heirline.nvim/blob/master/cookbook.md#tablist, without bufferlist. It only makes sense to display `tabline` if there is more than one tab, but heirline overrides my `showtabline = 1` to `2` in https://github.com/rebelot/heirline.nvim/blob/5b72a6a612707ada7ae71c4e8985e2148331cfe9/lua/heirline/init.lua#L57.

Could that line be removed giving users greater control?

Thanks!

**Comment by rebelot** [comment]
I could do it, but you can simply reinforce your setting after calling hairline setup. If this does not cut it, I'll consider removing it

**Comment by gegoune** [comment]
It does work and this is what I am doing right now but it enforces certain order of things, for me it means that I have this one single option set in different file than all the other nvim options. Also required me to check the code of heirline to understand why my desired behaviour changed.

I can create PR with removal and quick mention of that option in cookbook maybe?
