### ISSUE TITLE
Component separators

### ISSUE THREAD

**Issue by axieax** [rebelot/heirline.nvim#75]
Hi, I'm currently migrating from galaxyline.nvim to heirline.nvim. I've got most of my statusline copied over, except for the concept of "separators" in galaxyline.nvim, for which I cannot find an equivalent for here. I've tried adding the Space component (" " provider) but that doesn't exactly achieve what I want, since some components may be empty conditionally, causing there to be more spaces than intended in some cases, e.g.

```
Component 1
Space
Component 2
Space
Component 3
```

If Component 2 is conditionally empty, then this will be:

```
Component 1
Space
Space
Component 3
```

However, I want this to be without the extra space, i.e.

```
Component 1
Space
Component 3
```

Is it possible to achieve something like this with this plugin, or would this be a feature request? Thanks!

**Comment by rebelot** [comment]
It is definitely possible, the only thing that matters is where you put the `Space` component. If the component is conditional, then the `Space`r should be inserted within the block containing the condition, for example:

```lua
  my_conditional_component = {
    provider = 'something',
    condition = function() ... end,
    Space
```

If you don't want to modify the component, you can always use the utility `insert()` function, which will add provided children to a component, e.g.:

```lua
statusline = {
  ...
  utils.insert(my_conditional_component, Space)
  ...
```

**Comment by axieax** [comment]
Perfect thank you so much for the quick reply!
