### ISSUE TITLE
`on_click` doesn't work with child components

### ISSUE THREAD

**Issue by axieax** [rebelot/heirline.nvim#77]
I've been trying to add `on_click` events to child components of a main component, as well as main components which have child components, but they don't seem to work. Is there a way to achieve this without having to split it into multiple components?

**Comment by rebelot** [comment]
`on_click` _does work_ with child components, and the cookbook is dense with examples.

Can you please be more specific with your issue and provide an example of what you're trying to achieve?

**Comment by axieax** [comment]
Oh, not sure why it doesn't work for me. Sorry I forgot to attach my config: https://github.com/axieax/dotconfig/blob/main/nvim/lua/axie/plugins/statusline.lua

Every instance of "on_click" in that code does not seem to work for some reason.

**Comment by rebelot** [comment]
You should remove the spaces in on_click names. Those are the name of a global function that will be called on click from vim, and thus should contain only valid characters for a variable.

**Comment by axieax** [comment]
Omggg no wonder. Thanks for the clarification (took ages trying to debug this). Would be nice to see this in the docs as well :))
