### ISSUE TITLE
Using Highlight Groups rather than load_colors

### ISSUE THREAD

**Issue by mehalter** [rebelot/heirline.nvim#78]
I have a quick question. I'm sure I must be doing something wrong... I am currently using `load_colors` to set up colors for Heirline and for a simple example, I am getting the `fg` and `bg` of the `StatusLine` and setting that as the `hl` variable manually with something like this:

```lua
bg = utils.get_highlight("StatusLine").bg,
fg = utils.get_highlight("StatusLine").fg,
```

And then setting them as the topmost level `hl` with `hl = { fg = "fg", bg = "bg" }`. This works great but I am trying to move this to using the highlight group notation with strings, but when I do `hl = "StatusLine"` I am getting different results. I have verified that the `StatusLine` highlight group I have in my  theme only sets `fg` and `bg` and doesn't set anything like `reverse = true` or anything, but this is what I'm getting:

With  `hl = { fg = "fg", bg = "bg" }`:

![2022-10-21_09:13:48_screenshot](https://user-images.githubusercontent.com/1591837/197204322-7bfa7a09-a7db-40a1-af3e-c722ddcfa8bc.png)

With `hl = "StatusLine"`:

![2022-10-21_09:14:25_screenshot](https://user-images.githubusercontent.com/1591837/197204415-4250a0ed-2a7d-4f97-a6c2-465cc6b8aa25.png)

It seems to me like for some reason when I use the `hlgroup` notation the colors get reversed as well as bolded. I did some testing and this is what I get when I do `hl = { fg = "fg", bg = "bg", reverse = true }`:

![2022-10-21_09:15:28_screenshot](https://user-images.githubusercontent.com/1591837/197204612-d14e22c1-ab1d-437d-a64e-43fb12b7d5ac.png)

`hl = { fg = "fg", bg = "bg", reverse = true, bold = true }`:

![2022-10-21_09:16:34_screenshot](https://user-images.githubusercontent.com/1591837/197204874-7032a592-7431-46cf-ab6e-fa5df2f4c6ee.png)

Is there any reason for this to be happening or something I might be doing incorrectly?

**Comment by mehalter** [comment]
Hm as I opened this I am starting to think this is a problem with my `surround` function for some reason. I am investigating this currently

**Comment by mehalter** [comment]
I guess I'm still confused why changing a global highlight group from a manual definition to the `hlgroup` string definition would change behavior if they should be resolving to the same set of highlights. So maybe this is something else and not my own fault 🤔

**Comment by mehalter** [comment]
I think this has to do with the colors not updating when you reload the colorscheme. For example, if I do this:

```lua
hl = utils.get_highlight("StatusLine")
```

I get the same results as `hl = "StatusLine"`

but if I do

```lua
hl = function() return utils.get_highlight("StatusLine") end
```

it works as expected.

**Comment by rebelot** [comment]
When you use `hl = "HlName"` heirline calls `utils.get_highlight` at evaluation to be able to merge the highlight with the parent, so it will always pick up hl defined in the current theme.

When you use `hl = utils.get_highlight("HlName")` you are "hard coding" the returned values in the component definition, which are only valid for the current theme.

As you found out, wrapping it into a function allows re-evaluation of 'get_highlight` and updates correctly on colorscheme changes (as long as the hlgroup exists in the new theme).

The best way to ensure consistency on colorscheme changes is to never use the result of `utils.get_highlight` directly, instead, wrap it into a function, use hlgroups names directly, or use color name aliases defined in setup_colors with the instruction in the cookbook #theming.

Is there anything you think I could do?

**Comment by mehalter** [comment]
Hm, I guess I'm wondering why it doesn't seem to work correctly when I use the `hlgroup` name directly. Do you have any idea why that would be?

**Comment by mehalter** [comment]
The simplest example that illustrates this is

```lua
require("heirline").setup({ hl = "StatusLine", provider = "Hello, World!" })
```

**Comment by mehalter** [comment]
This results in:

![2022-10-21_13:32:14_screenshot](https://user-images.githubusercontent.com/1591837/197255199-dbbca29f-4ad9-47f3-8d99-b4d6ce21f842.png)

where if I specify the `fg`/`bg` directly or with the function calling `get_highlight` I get this:

```lua
require("heirline").setup({ hl = function() return utils.get_highlight("StatusLine") end, provider = "Hello, World!" })
```

![2022-10-21_13:33:34_screenshot](https://user-images.githubusercontent.com/1591837/197255377-5b8d7a3b-dd8a-4939-beb8-73b57eb16985.png)

**Comment by rebelot** [comment]
```lua
require("heirline").setup({ hl = "StatusLine", provider = "Hello, World!" })
```

gives me the expected result, _unless_ I load heirline config __before__ the intended colorscheme.

this is what I get with `nvim --clean --cmd 'hi StatusLine'`

<img width="484" alt="Screenshot 2022-10-22 at 02 35 18" src="https://user-images.githubusercontent.com/36300441/197308432-f79d29e8-6fa7-47bf-8c11-2af0c783f422.png">

The strange thing is that, for some reason, `bold` and `reverse` get stuck within the component highlight logic... I will investigate
