### ISSUE TITLE
Inactive StatusLine is not showing. A global Active statusline is shown instead.

### ISSUE THREAD

**Issue by RayZ0rr** [rebelot/heirline.nvim#83]
First of all:
@rebelot is a genius for making this plugin. This type of statusline,tabline,winbar setup is soooo customizable and feature rich. Although, it's a bit hard for new users to get into and takes time to configure. But it's probably set and done once.

I have the following config :
```lua
local ActiveStatusLine = {
  ViMode, Space, Left_filebar, FileNameBlock, Right_filebar, Space, Git,
  Align, TreesitterStatus, Space, LSPStatus, Align,
  Diagnostics, Space, Position, Space, FileTypeIcon, Space, ScrollBar, Space, FileFormat, FileEncoding, FileSize, Space, OSMode
}
local InactiveStatusLine = {
  condition = conditions.is_not_active,
  Left_filebar, FileNameBlock, Right_filebar, Space, Git,
}
local SpecialStatusLine = {
  condition = function()
    return conditions.buffer_matches({
      buftype = { "prompt", "help", "quickfix" },
      filetype = special_filetypes,
    })
  end,
  Space, InactiveMode, InactiveSep, ViMode, Space, Left_filebar, InactiveFiletype, Right_filebar
}

local StatusLine = {
  fallthrough = false,
  SpecialStatusLine, InactiveStatusLine, ActiveStatusLine
}
```

With this I get `ActiveStatusLine` normally:

![image](https://user-images.githubusercontent.com/96843787/198042190-43fe07bb-4596-4aad-ac40-a68f32c5229b.png)

and `SpecialStatusLine`

![image](https://user-images.githubusercontent.com/96843787/198042428-1ef59b04-e8a9-4dde-ab06-6258fe117ccc.png)

But I get only one global statusline when doing splits:

![image](https://user-images.githubusercontent.com/96843787/198042660-2d1641f2-c46f-4c82-874a-c497f529b4e1.png)

How to show Activestatusline in active window and Inactive in the inactive one.

**Comment by RayZ0rr** [comment]
That was indeed the problem. Thanks for the help.

**Comment by RayZ0rr** [comment]
Using :

`set laststatus=2` disables floating windows from having a statusline. Now floating windows like fzf shows the statusline of the window behind it. Is there a workaround for this?

`set laststatus=3` enables statusline for floating windows but disables it for split windows.

How to achieve the best of both worlds? Is there any autcommand to temporarily switch `laststatus` when floating windows open or splits open?

![image](https://user-images.githubusercontent.com/96843787/198526853-a52f13b6-e529-436a-8204-e88bd8473722.png)

**Comment by rebelot** [comment]
I am not sure this is an issue, but I think this might work.

```lua
vim.api.nvim_create_autocmd({ "WinEnter", "WinClosed" }, {
    callback = function()
        local winid = vim.api.nvim_get_current_win()
        if vim.api.nvim_win_get_config(winid).zindex then
            vim.o.laststatus = 3
        else
            vim.o.laststatus = 2
        end
    end,
})
```
