### ISSUE TITLE
Winbar problems with Hydra.nvim

### ISSUE THREAD

**Issue by DrKGD** [rebelot/heirline.nvim#88]
In a very specific use-case with [hydra.nvim](https://github.com/anuvyklack/hydra.nvim), winbar appears, when it should not

Not really a clue how to track it down, I suppose i could give a MRE

```lua
local hydra = require("hydra")

local on	= ' '
local off =	' '

local make_check = function(lambda)
	return function()
		return (lambda() and on) or off
	end
end

local hint = {
		'ﮢ   ^ ^             Neovim editor options',
		' %{li} _~_                     Toggle list',
}

local h = hydra({
	name = 'Window control',
	mode = 'n',
	hint = table.concat(hint, '\n'),
	config = {
		color = 'red',
		invoke_on_body = true,
		hint = {
			position = 'middle',
			border = 'rounded',
			funcs = {
				li = make_check(function() return vim.opt.list._value end)
			}
		},
	},
	heads = {
		{'~', function() vim.opt.list = not vim.opt.list._value end },

		-- (Exit)
		{ "<Esc>", nil, { exit = true, desc = false}},
	}
})

vim.api.nvim_create_user_command('HydEditor', function() h:activate() end, { })
```

Upon running `:HydEditor`
![image](https://user-images.githubusercontent.com/44092476/201186071-bbec5479-1bd1-4121-9b26-ad3ae0b317ad.png)

Upon using one of hydra's heads (the only available `~`)
![image](https://user-images.githubusercontent.com/44092476/201186100-284d8715-1481-4fe7-aca5-f917c9e20f92.png)

I followed the instructions at disabling winbar for certain filetypes [@cookbook](https://github.com/rebelot/heirline.nvim/blob/master/cookbook.md#winbar), thus I have it disabled for which would appear as `hydra_hint` in the source code
```lua
local winbar = { }
	winbar.fallthrough = false

-- Check if special buffer, thus don't display anything
winbar[1] = {
	condition = function()
			return cond.buffer_matches({
					buftype =  {"prompt", "quickfix"},
					bufname = { ".*Wilder Float.*" },
					filetype = {"^git.*", "hydra_hint", "plaintext"}
				})
		end,

	init = function()
		vim.opt_local.winbar = nil
	end,
}

-- Default winbar 
winbar[2] = { ... }

-- Apply
require("heirline").setup(status or { }, winbar)
```

While it works perfectly for some other plugins like `LSPSaga`, configuration seems to have no effect for `Hydra.nvim`, should I forward this issue to them as well?

Oddly enough, if I use the so-called [temporary fix](https://github.com/rebelot/heirline.nvim/issues/47#issuecomment-1211815471) it works just fine, thus the `hydra hint` is correcly updated, with or without the `cond.buffer_matches` condition, so I suppose it doesn't really matter in this context.

![image](https://user-images.githubusercontent.com/44092476/201187752-4a5619b0-f451-4269-aef1-327c729f1e37.png)
![image](https://user-images.githubusercontent.com/44092476/201187777-8a5d2d62-0814-4b59-9219-48c70e1ca16d.png)

I suppose `hydra` plugin itself updates the buffer and somehow it triggers the winbar to update its configuration?
If it is of any help, hydra provides an `on_enter` and `on_exit` clause for the hydra component, thus runs, you guessed it, a function when the gui is displayed or closed.

**Comment by rebelot** [comment]
Have you tried setting up the user autocmd as explained in the cookbook?

**Comment by DrKGD** [comment]
Uh!
Actually I did not think much of it until now and it seems to work just fine, guess this is the only way to override whatever either nvim or hydra is doing under the hood with the buffer 🤨

Again, thanks a lot for the quick solution (sorry about the useless issue thought)!

**Comment by rebelot** [comment]
No worries;) the autocmd is the recommended way to do that, insetting it from the winbar itself is more of a fail safe but sometimes it's flaky
