### ISSUE TITLE
`get_highlight` function from the `heirline.utils` module seems to be broken

### ISSUE THREAD

**Issue by atchim** [rebelot/heirline.nvim#9]
After a long time attempting to figure out why my status line was unable to be printed the same way as `StatusLineNC` defines, I noticed that the highlight group `StatusLineNC` had `guibg=0c0c0c`, but when calling `utils.get_highlight'StatusLineNC'` the `bg` field of the returned table is set to `c0c0c`.

I've checking this behavior and seems that this function actually deletes a leading zero from the  highlight attribute values.

**Comment by arsham** [comment]
See [this](https://github.com/rebelot/heirline.nvim/pull/8) PR.

**Comment by rebelot** [comment]
can you please update and see if it's still a problem? It should be fixed now.

**Comment by atchim** [comment]
Working properly now, really thanks!
