### ISSUE TITLE
Winbar flashes before being closed

### ISSUE THREAD

**Issue by gegoune** [rebelot/heirline.nvim#91]
Hi! I have set up simple winbar using heirline with `fallback = false` so I can disable it for certain buffer types or filetypes.
Generally it works except for one visual annoyance. When opening window matching first component group (as below) it has winbar set to some value before it gets set to `nil`, resulting in visual flash and then content shift. Is it something to do with my setup perhaps or can you reproduce? 

My config is:
```lua
return {
  fallthrough = false,
  { -- Hide the winbar for special buffers
    condition = function()
      return conditions.buffer_matches {
        buftype = { 'nofile', 'prompt', 'help', 'quickfix' },
        filetype = { '^git.*', 'mail' },
      }
    end,
    init = function() vim.opt_local.winbar = nil end,
  },
  { FileNameBlock, Align, utils.insert(Diagnostics, Space), Git },
}
```
which then get passed as second argument of `setup()`.

**Comment by rebelot** [comment]
Have you tried setting up the auto command? see the example [here](https://github.com/rebelot/heirline.nvim/blob/master/cookbook.md#winbar)

**Comment by gegoune** [comment]
Thanks for coming back to me. Adding auto command does fix the issue. Wasn't really sure it was needed as doc says: 
>This can be accomplished directly by Heirline during component evaluation (see example below) and/or by defining your own autocommands somewhere else

so I assume that I am fulfilling that requirement (and/or) by having that fallback as in docs and above.

Could you please confirm that auto command is strictly necessary? Thanks!

**Comment by rebelot** [comment]
Yes, the auto command is the preferred way, as it happens immediately when the winbar is set for the window. I will update the cookbook to make it clearer that the autocommand is non optional for optimal behaviour
