### ISSUE TITLE
question regarding code

### ISSUE THREAD

**Issue by max397574** [rebelot/heirline.nvim#95]
in `StatusLine:new()` there are a few lines like this `y = vim.tbl_extend("keep",x,{})`
as far as I know this does absolutely nothing. You could just do `y = x`.
any reason why this is done?

**Comment by rebelot** [comment]
It copies the table into a new one. This is needed to ensure no references are shared between the config and the statusline object.

**Comment by max397574** [comment]
`vim.deepcopy`?
